import "./globals.css";
import { Inter } from "next/font/google";
import { Provider } from "react-redux";
import store from "../store/store";
import dotenv from "dotenv";

dotenv.config();

const inter = Inter({ subsets: ["latin"] });

const RootLayout = ({ children }) => {
  return (
    <Provider store={store}>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </Provider>
  );
};

export default RootLayout;

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
